module.exports = {
  hello: "hello，welcome to MIOT Extension development !",
  selfDefineScene: "custom scene",
  timeSetting: "time setting",
  countDownTime: "countdown time",
  mijia: "SmartHome",
  on: "on",
  off: "off",
  commonSetting: "commonSetting",
  "Current power status": "Current power status",
  On: "On",
  "Power on status": "Power on status",
  Remain: "Remain",
  Off: "Off",
  "Atmosphere lamp": "Atmosphere lamp",
  Switch: "Switch",
  "Function set": "Function set",
  "Power on status set": "Power on status set",
  "Atmosphere lamp Switch": "Atmosphere lamp Switch",
  "Click too fast, please wait a second.":
    "Click too fast, please wait a second.",
  "Device is offline": "Device is offline",
  "The device is offline, please check whether the device is connected to the Bluetooth Mesh gateway!":
    "The device is offline, please check whether the device is connected to the Bluetooth Mesh gateway!",
  Confirm: "Confirm",
  Cancel: "Cancel",
};
