module.exports = {
  hello: "你好，欢迎加入 MIOT 扩展程序开发!",
  selfDefineScene: "自定义场景",
  timeSetting: "时间设置",
  countDownTime: "倒计时",
  mijia: "米家",
  on: "打开",
  off: "关闭",
  commonSetting: "功能设置",
  "Current power status": "当前电源",
  On: "开启",
  "Power on status": "上电状态",
  Remain: "记忆",
  Off: "关闭",
  "Atmosphere lamp": "氛围灯",
  Switch: "开关",
  "Function set": "功能设置",
  "Power on status set": "上电状态设置",
  "Atmosphere lamp Switch": "氛围灯开关",
  "Click too fast, please wait a second.": "点击太快，请稍后...",
  "Device is offline": "设备已离线",
  "The device is offline, please check whether the device is connected to the Bluetooth Mesh gateway!":
    "设备离线，请检查设备是否连接蓝牙Mesh网关！",
  Confirm: "确定",
  Cancel: "取消",
};
